/* Auto-generated by tools/gen_ui_text.py -- edit LABELS there. */
#ifndef UI_TEXT_H
#define UI_TEXT_H

/* UTF-8 UI labels (octal escapes keep this file pure ASCII).
 * The first comment on each line lists the unicode codepoints. */

/* U+53CC U+6838 U+793A U+6CE2 U+5668 : product name  \u53cc\u6838\u793a\u6ce2\u5668 */
#define S_TITLE       "\345\217\214\346\240\270\347\244\272\346\263\242\345\231\250"
/* U+65F6 U+57FA : time/div  \u65f6\u57fa */
#define S_TIMEBASE    "\346\227\266\345\237\272"
/* U+7535 U+538B : volts/div  \u7535\u538b */
#define S_VDIV        "\347\224\265\345\216\213"
/* U+91C7 U+6837 : sample rate  \u91c7\u6837 */
#define S_SRATE       "\351\207\207\346\240\267"
/* U+8FD0 U+884C : running  \u8fd0\u884c */
#define S_RUN         "\350\277\220\350\241\214"
/* U+505C U+6B62 : stopped  \u505c\u6b62 */
#define S_STOP        "\345\201\234\346\255\242"
/* U+901A U+9053 U+0031 : channel 1  \u901a\u90531 */
#define S_CH1         "\351\200\232\351\201\2231"
/* U+901A U+9053 U+0032 : channel 2  \u901a\u90532 */
#define S_CH2         "\351\200\232\351\201\2232"
/* U+83DC U+5355 : menu title  \u83dc\u5355 */
#define S_MENU        "\350\217\234\345\215\225"
/* U+9000 U+51FA : exit  \u9000\u51fa */
#define S_EXIT        "\351\200\200\345\207\272"
/* U+5F00 : on  \u5f00 */
#define S_ON          "\345\274\200"
/* U+5173 : off  \u5173 */
#define S_OFF         "\345\205\263"
/* U+89E6 U+53D1 : trigger enable  \u89e6\u53d1 */
#define S_TRIG        "\350\247\246\345\217\221"
/* U+8FB9 U+6CBF : trigger edge  \u8fb9\u6cbf */
#define S_EDGE        "\350\276\271\346\262\277"
/* U+4E0A U+5347 : rising edge  \u4e0a\u5347 */
#define S_RISE        "\344\270\212\345\215\207"
/* U+4E0B U+964D : falling edge  \u4e0b\u964d */
#define S_FALL        "\344\270\213\351\231\215"
/* U+7535 U+5E73 : trigger level  \u7535\u5e73 */
#define S_LEV         "\347\224\265\345\271\263"
/* U+6A21 U+5F0F : trigger mode  \u6a21\u5f0f */
#define S_MODE        "\346\250\241\345\274\217"
/* U+81EA U+52A8 : auto mode  \u81ea\u52a8 */
#define S_AUTO        "\350\207\252\345\212\250"
/* U+5E38 U+6001 : normal mode  \u5e38\u6001 */
#define S_NORM        "\345\270\270\346\200\201"
/* U+5355 U+6B21 : single mode  \u5355\u6b21 */
#define S_SINGL       "\345\215\225\346\254\241"
/* U+6D4B U+91CF : measurement  \u6d4b\u91cf */
#define S_MEAS        "\346\265\213\351\207\217"
/* U+6CE2 U+5CF0 : wave-peak  \u6ce2\u5cf0 */
#define S_VPP         "\346\263\242\345\263\260"
/* U+5E73 U+5747 : average  \u5e73\u5747 */
#define S_VAVG        "\345\271\263\345\235\207"
/* U+9891 U+7387 : frequency  \u9891\u7387 */
#define S_FREQ        "\351\242\221\347\216\207"
/* U+5360 U+7A7A U+6BD4 : duty cycle  \u5360\u7a7a\u6bd4 */
#define S_DUTY        "\345\215\240\347\251\272\346\257\224"

#endif /* UI_TEXT_H */
